name: twiml
version: 0.0.0
description: TwiML generators for Dart.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/dart-twiml
environment:
    sdk: ">=1.19.0"
dev_dependencies:
    angel_framework: ^1.0.0-dev
    angel_test: ^1.0.0-dev
    test: ^0.12.15
    xml: ^2.5.0